### ISSUE TITLE
Adding shiny app

### ISSUE THREAD

**Issue by romatik** [tracking-exposed/dashboard#11]
Should I create a new repo for shiny app or add it here?

**Comment by vecna** [comment]
Hi @romatik :) 

The shiny app in R is good in the dashboard, feel free to upload a directory with description on how we can use it.

We should address a proper refactoring and restructuring of this package. I imagine:

  * we should offer some scripts meant to download the data (in CSV and JSON) 
  * the package should include different analysis method. Shiny app is one of them, python notebook with pandas is another one, etc...

Feel free to commit! thanks
