### ISSUE TITLE
wizard.py should be the "landing script", should setup all configurations

### ISSUE THREAD

**Issue by berli0z** [tracking-exposed/dashboard#16]

**Comment by vecna** [comment]
to be honest, I don't feel a strong case to use `wizard.py`, at the moment is creating a file with precompiled options (which helps, indeed), but:
  * the options should be known by the users of the scripts, the config file contain some of these, the risk is dis-aligning knowledge
  * and the option should become more standard as possible, used by all the scripts

This comment do not contains actionable steps, just sharing!
