### ISSUE TITLE
restructuring of README.md

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/dashboard#20]
should be logically separated:
  * installation procedure (github wiki)
  * usage hints (github wiki)
  * what is this package about, high level meanings and requirements (README.md)

**Comment by vecna** [comment]
https://github.com/tracking-exposed/dashboard/wiki/installing-python-dashboard

**Comment by vecna** [comment]
https://github.com/tracking-exposed/dashboard/wiki/usage-(entry-level)

**Comment by berli0z** [comment]
Edited, leaving your notes here for reference:
  * what is this repository about
    * supporting datascientists
    * this is the intermediate step between research and realitycheck
    * this is mean to find new narratives on algorithm
  * for who is meant 
   * datascientist
   * it analyzes youtube and facebook and all the other tracking.exposed supported services
  * all the resources are in the same repository 
   * installation (link)
   * how to use the tools (link)
   * possible output (link)

**Comment by vecna** [comment]
thanks!
