### ISSUE TITLE
Parsing "Your Facebook Information" to retrieve users' liking activity

### ISSUE THREAD

**Issue by davidberra** [tracking-exposed/dashboard#25]
this converts the json that FB provides a user with their activity into a USER/DATE/PAGE/REACTION_TYPE/POST_TYPE dataframe

to do: *deal with absolute paths; *integrate in pandas dataframe

**Comment by davidberra** [comment]
import json
import pandas as pd
import os
from datetime import datetime


def title2page(title):
    page = ''
    if ' reacted to ' in title: page = title.split(' reacted to ')[1].split("'s")[0]
    else: page = title.split(' likes ')[1].split("'s")[0]
    return page



def parseFields(user):
    likes_f = open('facebook-'+user+'/likes_and_reactions/posts_and_comments.json')
    likes_json = json.load(likes_f)
    for like in likes_json['reactions']:
        try:
            user = user
            date_time = datetime.fromtimestamp(like['timestamp'])
            page = title2page(like['title'])
            reaction_type = like['data'][0]['reaction']['reaction']
            post_type = like['title'].split(':')[0].split(page+"'s ")[1].strip('.')
        except: pass
        print(user,date_time,page,reaction_type,post_type)

        

for dir in os.listdir():
    if 'facebook-' in dir: like_per_time = parseFields(dir[9:])

**Comment by berli0z** [comment]
Thanks @davidberra ! I'm adding a script in `scripts/fb_your_likes.py`

It will create a csv that contains data about what likes you did on facebook, so you can compare it to what you are seeing.

it should have this format:
```
+-----------------+---------------+---------+----------------+----------------+
|       DATETIME      |     REACTION   |    USER   |    POST_TYPE    |    SOURCE        |
+-----------------+---------------+---------+----------------+----------------+
| 19-11-19  22:33:44  |       LIKE      |  tapioca   |       photo       |       theguardian    |
+-----------------+---------------+---------+----------------+-----------------+
```
