### ISSUE TITLE
create a function to download API data

### ISSUE THREAD

**Issue by berli0z** [tracking-exposed/dashboard#5]
it needs to be able to:
- [x] call different APIs
- [x] select a timeframe
- [x] implement caching
- [x] save in either csv and/or json format
- [x] choose a saving path
- [x] run from command line
- [x] run with crontab

arguments:
- [x] amount of data entries
- [x] amount to skip
- [x] which data? summary? etc
- [x] start-end date?
- [x] json or csv
- [x] save path

**Comment by berli0z** [comment]
The function implemented in the commit https://github.com/tracking-exposed/dashboard-git/commit/b705f8c822b0add09f6a708c5017f8589232bff3 does not take into account the use case of a user wanting to get data periodically with relative datetime values as start and end date.
we should address this by
- adding the chance of choose how many days to go behind instead of specifying a startdate?
- use only relative start/end dates?
- leave it as it is and let the researchers use bash to call the proper timeframe?

**Comment by vecna** [comment]
A new API which can help in this, has been implemented here: https://github.com/tracking-exposed/facebook/issues/126

if you connect to `https://testing.tracking.exposed/api/v2/<token>/stats/<optional paging>`

you might see a result coming from the timelines. The pipeline of the mongodb query is:

1) look at the $paging timelines, default 20-0 (amount 20, skip 0)
2) look at all the impression collected per timeline (in your case, should be an average of 40?)
3) look at the metadata attributed by the parsers

Imagine to call a query 5 minutes after the scheduled refresh of your bots. then:

based on 1, if the call do not return new timelines -> the bots are down
based on 2, if the call do not return enough impression -> bots working bad
based on 3, if the call has not metadata but impression -> parsers are broken
